train:
  _target_: src.datasets.LibrispeechDataset
  part: "train-other-500"
  data_dir:
    _target_: pathlib.Path
    _args_:
      - "/kaggle/input/librispeech/train-clean-100/LibriSpeech"
  index_dir:
    _target_: pathlib.Path
    _args_:
      - "/kaggle/working/dla_hw1_asr/saved"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-other"
  data_dir:
    _target_: pathlib.Path
    _args_:
      - "/kaggle/input/librispeech/train-clean-100/LibriSpeech"
  index_dir:
    _target_: pathlib.Path
    _args_:
      - "/kaggle/working/dla_hw1_asr/saved"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.LibrispeechDataset
  part: "test-other"
  data_dir:
    _target_: pathlib.Path
    _args_:
      - "/kaggle/input/librispeech/train-clean-100/LibriSpeech"
  index_dir:
    _target_: pathlib.Path
    _args_:
      - "/kaggle/working/dla_hw1_asr/saved"
  instance_transforms: ${transforms.instance_transforms.inference}