train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)" # it is better to avoid spaces in names
    use_beam_search: False
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
    use_beam_search: False
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax) with beam search" # it is better to avoid spaces in names
    use_beam_search: True
    beam_size: 3
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax) with beam search"
    use_beam_search: True
    beam_size: 3
    