defaults:
  - model: deepspeech
  - writer: wandb
  - metrics: example
  - datasets: kaggle_clean
  - dataloader: example
  - transforms: augment
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: ${trainer.epoch_len}
  gamma: 0.97
loss_function:
  _target_: src.loss.CTCLossWrapper
  zero_infinity: True
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  use_bpe_tokenizer: False
trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: 1
  sample_rate: 16000
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  resume_from: null  # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto  # device name or "auto"
  override: True  # if True, will override the previous run with the same name
  monitor: "min val_WER_(Argmax)"  # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5  # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  from_pretrained: "saved/model_best.pth"  # "saved/model_best.pth" # path to the pretrained model
  seed: 1