defaults:
  - model: deepspeech
  - metrics: inference
  - datasets: eval_clean # we do not want to run inference on training data
  - dataloader: example
  - transforms: clean
  - _self_
text_encoder:
  _target_: src.text_encoder.CTCTextEncoder
  lm_decoding: True
inferencer:
  device_tensors: ["spectrogram", "text_encoded"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "inference_test" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/model_best_augm.pth" # path to the pretrained model